from pathlib import Path

import pandas as pd
import pytest
from rdflib import Literal, URIRef

from expl_annotator import ProvOneManager


@pytest.fixture()
def manager(tmp_path):
    config_path = tmp_path / "config.yaml"
    config_path.write_text(
        """
program:
  name: TestProg

ttl:
  save_path: provenance.ttl
  metadata_path: metadata.json
  prefixes:
    - name: TestProg
      uri: http://example.org/test#
    - name: provone
      uri: http://purl.dataone.org/provone/2015/01/15/ontology#
    - name: prov
      uri: http://www.w3.org/ns/prov#
    - name: rdfs
      uri: http://www.w3.org/2000/01/rdf-schema#
    - name: sio
      uri: http://semanticscience.org/resource/
    - name: workflow
      uri: http://www.semanticweb.org/acer/ontologies/2026/1/WorkFlow/
    - name: xsd
      uri: http://www.w3.org/2001/XMLSchema#
    - name: DFColumn
      uri: http://example.org/df#
    - name: dc
      uri: http://purl.org/dc/elements/1.1/
""".lstrip(),
        encoding="utf-8",
    )
    return ProvOneManager(config_path)


def uri(manager, curie):
    return URIRef(manager.curie(curie))


def test_program_ai_task_creates_llm_provenance(manager):
    program = manager.prov_program(
        "generated_function",
        has_in_port={"prompt": {"name": "prompt"}},
        has_out_port={"result": {"name": "result"}},
        metadata={"dc:description": "Generated function"},
        is_ai_task=True,
        ai_task={
            "llm_model": "gpt-4o",
            "input": {"prompt": "Create a function"},
            "metadata": {"dc:description": "Generated by an LLM"},
        },
    )

    task = uri(manager, "TestProg:Generative_Task-generated_function")
    method = uri(manager, "TestProg:LLM-generated_function")
    output = uri(manager, "TestProg:LLM_Output-generated_function")
    program_node = uri(manager, program["name"])

    assert (task, uri(manager, "a"), uri(manager, "workflow:Generative_Task")) in manager.graph
    assert (method, uri(manager, "a"), uri(manager, "workflow:Large_Language_Models")) in manager.graph
    assert (output, uri(manager, "a"), uri(manager, "workflow:Large_Language_Model_Output")) in manager.graph
    assert (task, uri(manager, "prov:used"), method) in manager.graph
    assert (output, uri(manager, "sio:SIO_000202"), program_node) in manager.graph
    assert program["aiTask"]["llm_model"] == "gpt-4o"


def test_program_execution_records_collections_members_and_ai_usage(manager):
    program = manager.prov_program(
        "runtime_function",
        has_in_port={
            "prompt": {"name": "prompt"},
            "items": {"name": "items"},
        },
        has_out_port={
            "answer": {"name": "answer"},
            "rows": {"name": "rows"},
        },
    )

    execution = manager.prov_program_execution(
        program,
        inputs={
            "prompt": {"data_type": "literal", "value": "hello"},
            "items": {"data_type": "list", "value": ["alpha", "beta"]},
        },
        outputs={
            "answer": {"data_type": "literal", "value": "world"},
            "rows": {"data_type": "data_frame", "value": pd.DataFrame({"score": [1, 2]})},
        },
        user="test_user",
        uses_ai=True,
        used_ai_info={
            "llm_model": "gpt-4o",
            "input": {"prompt": "hello", "items": ["alpha", "beta"]},
            "output": {"answer": "world", "rows": "rows"},
            "metadata": {"dc:description": "Runtime LLM use"},
        },
    )

    graph = manager.graph
    execution_node = uri(manager, execution["name"])
    collection_type = uri(manager, "provone:Collection")
    member_pred = uri(manager, "provone:hadMember")
    ai_task_type = uri(manager, "workflow:Generative_Task")
    llm_output_type = uri(manager, "workflow:Large_Language_Model_Output")

    assert any(obj == collection_type for _, _, obj in graph.triples((None, uri(manager, "a"), None)))
    assert any(graph.triples((None, member_pred, None)))
    assert any(obj == ai_task_type for _, _, obj in graph.triples((None, uri(manager, "a"), None)))
    assert any(obj == llm_output_type for _, _, obj in graph.triples((None, uri(manager, "a"), None)))
    assert any(graph.triples((execution_node, uri(manager, "sio:SIO_000369"), None)))

    prompt_data = uri(manager, execution["inputs"]["prompt"]["name"])
    assert (prompt_data, uri(manager, "rdfs:label"), Literal("prompt", datatype=uri(manager, "xsd:string"))) in graph

    items = execution["inputs"]["items"]
    assert "usage_name" in items["collection"]["components"]
    for member in items["members"]:
        assert (uri(manager, items["collection"]["name"]), member_pred, uri(manager, member["name"])) in graph

    rows = execution["outputs"]["rows"]
    assert "generation_name" in rows["collection"]["components"]
    assert len(rows["members"]) == 2


def test_metadata_must_be_string(manager):
    with pytest.raises(ValueError, match="Metadata values must be strings"):
        manager.add_metadata_to_object("TestProg:thing", {"dc:description": 123})


def test_add_to_namespace_updates_config_and_graph_binding(manager):
    manager.add_to_namespace("ex", "http://example.org/extra#")

    assert manager.config["namespaces"]["ex"] == "http://example.org/extra#"
    assert manager.namespaces["ex"] == "http://example.org/extra#"
    assert manager.curie("ex:item") == "http://example.org/extra#item"
